# Datasource
datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/rest
  url-flyway: jdbc:postgresql://localhost:54321/rest
  username: rest
  password: rest

# Log4j Configuration
log4j:
  rootLogger: INFO
  appender:
    file: org.apache.log4j.RollingFileAppender
  File: log/application.log
  layout: org.apache.log4j.PatternLayout
  ConversionPattern: '[%t] %-5p %c %x - %m%n'
