version: "3"

services:
  tomcat:
    build:
      context: ./
      dockerfile: ./docker/tomcat/Dockerfile
    container_name: tomcat
    environment:
      JAVA_OPTS: -Dspring.profiles.active=dev
    links:
      - postgres
      - postgres-test
    volumes:
    - ./docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./docker/tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    - ./api/build/libs/rest-api-basics.war:/usr/local/tomcat/webapps/rest-api-basics.war
    ports:
      - 8082:8080

  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=rest
      - POSTGRES_USER=rest
      - POSTGRES_DB=rest
      - PGDATA=/pg-data
    ports:
      - 54321:5432
    volumes:
      - pg-data:/pg-data

  postgres-test:
    container_name: postgres-test
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=rest-test
      - POSTGRES_USER=rest-test
      - POSTGRES_DB=rest-test
      - PGDATA=/pg-data-test
    ports:
      - 54322:5432
    volumes:
      - pg-data-test:/pg-data-test

volumes:
  pg-data:
  pg-data-test:
